Map<String, DSBSubject> dsbSubjectMapPretty = {
  '---': DSBSubject.entfaellt,
  'Englisch': DSBSubject.englisch,
  'Mathematik': DSBSubject.mathematik,
  'Kunst': DSBSubject.kunst,
  'Deutsch': DSBSubject.deutsch,
  'Latein': DSBSubject.latein,
  'Französisch': DSBSubject.franzoesisch,
  'Chemie': DSBSubject.chemie,
  'Chemie (Übungen)': DSBSubject.chemieUebung,
  'Evangelische Religionslehre': DSBSubject.evReligion,
  'Katholische Religionslehre': DSBSubject.kathReligion,
  'Physik': DSBSubject.physik,
  'Ethik': DSBSubject.ethik,
  'Geografie': DSBSubject.geografie,
  'Geschichte': DSBSubject.geografie,
  'Biologie': DSBSubject.biologie,
  'Musik': DSBSubject.musik,
  'Sport (w)': DSBSubject.sportW,
  'Sport (m)': DSBSubject.sportM,
  'Wirtschaft und Recht': DSBSubject.wirtschaftUndRecht,
  'Informatik': DSBSubject.informatik,
  'Sozialkunde': DSBSubject.sozialkunde,
  'Pause': DSBSubject.pause
};

Map<String, DSBSubject> dsbSubjectMap = dsbSubjectMapPretty.map((key, value) => MapEntry(key.toLowerCase(), value));

Map<DSBSubject, String> dsbSubjectShortPretty = {
  DSBSubject.entfaellt: '-',
  DSBSubject.englisch: 'E',
  DSBSubject.mathematik: 'M',
  DSBSubject.kunst: 'K',
  DSBSubject.deutsch: 'D',
  DSBSubject.latein: 'L',
  DSBSubject.franzoesisch: 'Fr',
  DSBSubject.chemie: 'Ch',
  DSBSubject.chemieUebung: 'Ch-Ü',
  DSBSubject.evReligion: 'EvR',
  DSBSubject.kathReligion: 'KtR',
  DSBSubject.physik: 'Ph',
  DSBSubject.ethik: 'Eth',
  DSBSubject.geografie: 'Geo',
  DSBSubject.geschichte: 'G',
  DSBSubject.biologie: 'Bio',
  DSBSubject.musik: 'Mu',
  DSBSubject.sportW: 'Sp',
  DSBSubject.sportM: 'Sp',
  DSBSubject.wirtschaftUndRecht: 'WuR',
  DSBSubject.informatik: 'Info',
  DSBSubject.sozialkunde: 'Sozi',
  DSBSubject.pause: ''
};

enum DSBSubject {
  unbekannt,
  englisch,
  mathematik,
  kunst,
  deutsch,
  latein,
  franzoesisch,
  chemie,
  chemieUebung,
  evReligion,
  ethik,
  kathReligion,
  physik,
  geografie,
  geschichte,
  biologie,
  entfaellt,
  musik,
  sportW,
  sportM,
  wirtschaftUndRecht,
  informatik,
  sozialkunde,
  pause
}

//OLD

Map<String, DSBSubject> _dsbSubjectMapOld = {
  '---': DSBSubject.entfaellt,
  'englisch': DSBSubject.englisch,
  'mathematik': DSBSubject.mathematik,
  'kunst': DSBSubject.kunst,
  'deutsch': DSBSubject.deutsch,
  'latein': DSBSubject.latein,
  'französisch': DSBSubject.franzoesisch,
  'chemie': DSBSubject.chemie,
  'chemie (übungen)': DSBSubject.chemieUebung,
  'evangelische religionslehre': DSBSubject.evReligion,
  'katholische religionslehre': DSBSubject.kathReligion,
  'physik': DSBSubject.physik,
  'ethik': DSBSubject.ethik,
  'geografie': DSBSubject.geografie,
  'geschichte': DSBSubject.geografie,
  'biologie': DSBSubject.biologie,
  'musik': DSBSubject.musik,
  'sport (w)': DSBSubject.sportW,
  'sport (m)': DSBSubject.sportM,
  'wirtschaft und recht': DSBSubject.wirtschaftUndRecht,
  'informatik': DSBSubject.informatik,
  'pause': DSBSubject.pause
};

Map<String, DSBSubject> _dsbSubjectShortPrettyOld = {
  '-': DSBSubject.entfaellt,
  'E': DSBSubject.englisch,
  'M': DSBSubject.mathematik,
  'K': DSBSubject.kunst,
  'D': DSBSubject.deutsch,
  'L': DSBSubject.latein,
  'Fr': DSBSubject.franzoesisch,
  'Ch': DSBSubject.chemie,
  'Ch-Ü': DSBSubject.chemieUebung,
  'EvR': DSBSubject.evReligion,
  'KtR': DSBSubject.kathReligion,
  'Ph': DSBSubject.physik,
  'Eth': DSBSubject.ethik,
  'Geo': DSBSubject.geografie,
  'G': DSBSubject.geografie,
  'Bio': DSBSubject.biologie,
  'Mu': DSBSubject.musik,
  'Sp': DSBSubject.sportW,
  'Sp': DSBSubject.sportM,
  'WR': DSBSubject.wirtschaftUndRecht,
  'Info': DSBSubject.informatik,
  'Sozi': DSBSubject.sozialkunde,
  '': DSBSubject.pause
};