Map<String, DSBSubject> dsbSubjectMap = {
  '---': DSBSubject.entfaellt,
  'englisch': DSBSubject.englisch,
  'mathematik': DSBSubject.mathematik,
  'kunst': DSBSubject.kunst,
  'deutsch': DSBSubject.deutsch,
  'latein': DSBSubject.latein,
  'französisch': DSBSubject.franzoesisch,
  'chemie': DSBSubject.chemie,
  'chemie (übungen)': DSBSubject.chemieUebung,
  'evangelische religionslehre': DSBSubject.evReligion,
  'katholische religionslehre': DSBSubject.kathReligion,
  'physik': DSBSubject.physik,
  'ethik': DSBSubject.ethik,
  'geografie': DSBSubject.geografie,
  'geschichte': DSBSubject.geografie,
  'biologie': DSBSubject.biologie,
  'musik': DSBSubject.musik,
  'sport (w)': DSBSubject.sportW,
  'sport (m)': DSBSubject.sportM,
  'wirtschaft und recht': DSBSubject.wirtschaftUndRecht,
  'informatik': DSBSubject.informatik,
  'pause': DSBSubject.pause
};

enum DSBSubject {
  unbekannt,
  englisch,
  mathematik,
  kunst,
  deutsch,
  latein,
  franzoesisch,
  chemie,
  chemieUebung,
  evReligion,
  ethik,
  kathReligion,
  physik,
  geografie,
  geschichte,
  biologie,
  entfaellt,
  musik,
  sportW,
  sportM,
  wirtschaftUndRecht,
  informatik,
  pause
}